openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: stream-controller
    description: Stream Controller
paths:
  /stream/meetup:
    get:
      tags:
        - stream-controller
      summary: getAllMeetups
      operationId: getAllMeetupsUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meetup'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - stream-controller
      summary: addMeetup
      operationId: addMeetupUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Meetup'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Meetup'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /stream/user:
    get:
      tags:
        - stream-controller
      summary: getAllUsers
      operationId: getAllUsersUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meetup'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - stream-controller
      summary: addUser
      operationId: addUserUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/User'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Meetup:
      title: Meetup
      type: object
      properties:
        category:
          type: string
        date:
          type: string
        description:
          type: string
        link:
          type: string
        meetupId:
          type: integer
          format: int32
        time:
          type: string
        title:
          type: string
        userId:
          type: integer
          format: int32
    User:
      title: User
      type: object
      properties:
        category:
          type: string
        description:
          type: string
        link:
          type: string
        title:
          type: string
        userId:
          type: integer
          format: int32